
services:
  web:
    image: devisingh/ecommerce-web:latest
    build: .
    container_name: ecommerce_web
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-change-me}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
    stdin_open: true
    tty: true
