# Generated by Django 5.2.12 on 2026-06-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_products_name_alter_products_price'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='products',
            index=models.Index(fields=['name', 'price'], name='myapp_produ_name_9c87a8_idx'),
        ),
    ]
