# Generated by Django 5.2.12 on 2026-06-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_products_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
